[package]
name = "simple-api-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
full = "0.3.0"
poem = "3.1.7"
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0.140"