apiVersion: v1
kind: Service
metadata:
  name: simple-api
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-api
  sessionAffinity: None
  type: ClusterIP
